from collections.abc import AsyncIterator
from typing import Protocol

from vibra.domain import (
    EnrichedTrack,
    OAuthToken,
    SavedTrack,
    SearchResults,
    SpotifyArtist,
    SpotifyUser,
)


class MusicLibrary(Protocol):
    async def current_user(self) -> SpotifyUser: ...
    async def read_liked_songs(self, max_tracks: int) -> AsyncIterator[SavedTrack]: ...
    async def get_artists(self, ids: list[str]) -> list[SpotifyArtist]: ...


class AuthProvider(Protocol):
    def get_auth_url(self) -> str: ...
    async def exchange_code(self, code: str) -> OAuthToken: ...
    async def cached_token(self) -> OAuthToken | None: ...
    async def refresh(self, refresh_token: str) -> OAuthToken: ...


class LyricsProvider(Protocol):
    async def fetch(self, *, title: str, artist: str) -> str: ...


class LLMProvider(Protocol):
    async def generate(self, prompt: str) -> str: ...


class VectorStore(Protocol):
    async def track_exists(self, track_id: str) -> bool: ...
    async def add(self, track: EnrichedTrack) -> None: ...
    async def add_many(self, tracks: list[EnrichedTrack]) -> None: ...
    async def search(self, query: str, n_results: int) -> SearchResults: ...
    async def count(self) -> int: ...
    async def delete(self, ids: list[str]) -> None: ...
